name: llm
channels:
  - moussi
  - psi4
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.2.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - binutils_impl_linux-64=2.31.1=h6176602_1
  - binutils_linux-64=2.31.1=h6176602_9
  - ca-certificates=2023.5.7=hbcca054_0
  - cachetools=5.3.0=pyhd8ed1ab_0
  - cloog=0.18.0=0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - gcc-5=5.2.0=1
  - gcc_impl_linux-64=7.3.0=hd420e75_5
  - gcc_linux-64=7.3.0=h553295d_9
  - gmp=6.2.1=h2531618_2
  - ipykernel=5.5.5=py39hef51801_0
  - ipython=8.14.0=pyh41d4057_0
  - ipython_genutils=0.2.0=py_1
  - isl=0.12.2=0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jupyter_client=7.1.2=pyhd8ed1ab_0
  - jupyter_core=5.3.1=py39hf3d152e_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libffi=3.3=he6710b0_2
  - libgcc-ng=7.3.0=hdf63c60_0
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h516909a_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nvidia-ml-py=11.525.112=pyhd8ed1ab_0
  - nvitop=1.1.2=py39hf3d152e_0
  - openssl=1.1.1k=h27cfd23_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.1.2=py39h06a4308_0
  - platformdirs=3.5.3=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - python=3.9.5=hdb3f193_3
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pyzmq=20.0.0=py39h2531618_1
  - readline=8.1=h27cfd23_0
  - setuptools=67.8.0=py39h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.35.4=hdfb4753_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - termcolor=2.3.0=pyhd8ed1ab_0
  - tk=8.6.10=hbc83047_0
  - tornado=6.1=py39h27cfd23_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.6.3=hd8ed1ab_0
  - typing_extensions=4.6.3=pyha770c72_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.38.4=py39h06a4308_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==2.1.0
    - accelerate==0.18.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - args==0.1.0
    - async-timeout==4.0.2
    - attrs==23.1.0
    - bayesian-optimization==1.4.3
    - certifi==2023.5.7
    - charset-normalizer==3.1.0
    - click==8.1.3
    - clint==0.5.1
    - cma==3.3.0
    - colorama==0.4.6
    - conda-pack==0.7.1
    - contourpy==1.1.0
    - coverage==7.4.4
    - cpm-kernels==1.0.11
    - cycler==0.11.0
    - datasets==2.12.0
    - deepspeed==0.9.4
    - dill==0.3.6
    - dnc==1.1.0
    - docopt==0.6.2
    - docstring-parser==0.15
    - einops==0.7.0
    - et-xmlfile==1.1.0
    - filelock==3.12.0
    - flann==1.6.13
    - fonttools==4.42.0
    - frozenlist==1.3.3
    - fsspec==2023.5.0
    - future==0.18.3
    - grpcio==1.62.0
    - hjson==3.1.0
    - huggingface-hub==0.20.1
    - icetk==0.0.7
    - idna==3.4
    - importlib-metadata==7.0.1
    - importlib-resources==6.0.1
    - jieba==0.42.1
    - joblib==1.2.0
    - jsonlines==3.1.0
    - kiwisolver==1.4.4
    - mamba==0.11.3
    - markdown==3.5.2
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.7.2
    - mdurl==0.1.2
    - multidict==6.0.4
    - multiprocess==0.70.14
    - nevergrad==0.13.0
    - ninja==1.11.1
    - nltk==3.8.1
    - numpy==1.24.3
    - openai==0.28.0
    - openpyxl==3.1.2
    - openyxl==0.1
    - packaging==23.1
    - pandas==2.0.1
    - pillow==9.5.0
    - pipreqs==0.4.13
    - protobuf==4.25.3
    - psutil==5.9.5
    - py-cpuinfo==9.0.0
    - pyarrow==12.0.0
    - pydantic==1.10.9
    - pyparsing==3.0.9
    - pytz==2023.3
    - pyyaml==6.0
    - rdkit==2023.9.1
    - regex==2023.6.3
    - requests==2.31.0
    - responses==0.18.0
    - rich==13.7.0
    - rouge-chinese==1.0.3
    - safetensors==0.3.1
    - scikit-learn==1.3.0
    - scipy==1.11.1
    - sentencepiece==0.1.99
    - setproctitle==1.3.3
    - shtab==1.6.5
    - sklearn==0.0.post5
    - tensorboard==2.16.2
    - tensorboard-data-server==0.7.2
    - threadpoolctl==3.1.0
    - tiktoken==0.6.0
    - tokenizers==0.13.3
    - torch==1.12.0+cu102
    - torchaudio==0.12.0+cu102
    - torchvision==0.13.0+cu102
    - tqdm==4.65.0
    - transformers==4.28.1
    - trl==0.7.6
    - tyro==0.6.1
    - tzdata==2023.3
    - urllib3==2.0.3
    - werkzeug==3.0.1
    - xxhash==3.2.0
    - yarg==0.1.9
    - yarl==1.9.2
    - zipp==3.16.2
prefix: /data/frankqdliu/anaconda3/envs/llm
